sudo: required

services:
    docker 

before_install:
    - docker build -t docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "dockerreact"
    env: "DockerReact-env"
    bucket: "elasticbeanstalk-us-east-2-251363892694"
    bucket_path: "dockerreact"
    on: 
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"